language: java

sudo: true

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  - KUBECTL_VERSION=v1.17.0
  - KUBECTL_VERSION=v1.16.4
  - KUBECTL_VERSION=v1.15.1
  - KUBECTL_VERSION=v1.14.3
  - KUBECTL_VERSION=v1.13.3
  - KUBECTL_VERSION=v1.12.9

install:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl

after_success:
- mvn clean test findbugs:check jacoco:report coveralls:report
